version: '3.7'
services:
  db:
    container_name: mariadb
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Dracu183
      MYSQL_DATABASE: docker
      MYSQL_USER: vulgaris
      MYSQL_PASSWORD: Dracu183
    networks:
      - db
  php:
    container_name: php-symfony
    build:
      dockerfile: ./php-fpm/Dockerfile
      context: .
    ports:
      - "9001:9000"
    depends_on:
      - db
    volumes:
      - ./logs/symfony:/var/www/symfony/var/log:cached
      - ./symfony:/var/www/symfony:cached

    networks:
      - db
      - php
  nginx:
    container_name: nginx-server
    build:
      dockerfile: ./nginx/Dockerfile
      context: .
    ports:
      - "81:80"
    depends_on:
      - php
    volumes:
      - ./symfony:/var/www/project
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx:cached
      - ./symfony:/var/www/symfony:cached
    networks:
      - php
networks:
  db:
  php:
