version: '3.7'
services:
  db:
    container_name: mariadb
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3305:3305"
    environment:
      MYSQL_ROOT_PASSWORD: Dracu183
      MYSQL_DATABASE: docker
      MYSQL_USER: vulgaris
      MYSQL_PASSWORD: Dracu183
    networks:
      - db
  php:
    container_name: php-symfony
    build: ./php-fpm
    ports:
      - "9001:9001"
    depends_on:
      - db
    networks:
      - db
      - php
  nginx:
    container_name: nginx-server
    build: ./nginx
    ports:
      - "81:81"
    depends_on:
      - php
    networks:
      - php
networks:
  db:
  php:
